[package]
description = "Renders a YAML lexicon file into a Markdown dictionary"
edition = "2021"
license = "MIT"
name = "lexi"
readme = "README.md"
repository = "https://github.com/jonathansharman/lexi"
version = "0.1.0"

[dependencies]
anyhow = "1.0.75"
clap = {version = "4.4.8", features = ["derive"]}
serde = {version = "1.0.192", features = ["derive"]}
serde_yaml = "0.9.27"
tera = {version = "1.19.1", default-features = false}
